# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: lint

on:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ################
  # Verible Lint #
  ################
  verible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chipsalliance/verible-linter-action@main
      with:
        config_file: ''
        paths: |
          ./hw
        extra_args: "--waiver_files util/verible.waiver"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        reviewdog_reporter: github-check

  ########
  # Ruff #
  ########
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3

  #########
  # REUSE #
  #########
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v5
