# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: publish-docs

on:
  # push:
    # branches: [ main ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: pip
      - name: Install Python requirements
        run: pip install .[docs]
      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
